apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-app
  namespace: test-app--staging
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kustomizations/test-app
  prune: true
  targetNamespace: test-app--staging
  images:
    - name: ghcr.io/scottaubrey/test-app
      newTag: 20250128074919.0.0-g983e61f-13005847665-1
  postBuild:
    substitute:
      # deployment vars
      hostname: test-app-staging.test.cluster
