apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-app
  namespace: test-app--staging
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kustomizations/test-app
  prune: true
  targetNamespace: test-app--staging
  images:
    - name: ghcr.io/scottaubrey/test-app
      newTag: 2b715f3c1f96c6f6ae2903a60d550c2b133caa6e
  postBuild:
    substitute:
      # deployment vars
      hostname: test-app-staging.test.cluster
