apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production
  namespace: test-app
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: github
    sources:
      stages:
      - staging
