apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: test-app
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: github
    sources:
      direct: true
  promotionTemplate:
    vars:
    - name: gitopsRepo
      value: https://github.com/scottaubrey/kargo-exploration
    - name: environment
      value: staging
    - name: imageTag
      value: ${{ imageFrom("scottaubrey/test-app").Tag }}
    steps:
    - uses: git-clone
      config:
        repoURL: ${{ vars.gitopsRepo }}
        checkout:
        - branch: main
          path: ./checkout
    - uses: yaml-update
      as: update-image
      path: ./checkout/manifests/test-app/${{ vars.environment }}/test-app.yaml
      updates:
      - key: .spec.images.1.newTag
        value: ${{ vars.imageTag }}
    - uses: git-commit
      as: commit
      config:
        path: ${{ vars.outPath }}
        messageFromSteps:
        - update-image
