apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: test-app
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: github
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/scottaubrey/kargo-exploration
          checkout:
          - branch: main
            path: ./checkout
      - uses: yaml-update
        as: update-image
        config:
          path: ./checkout/manifests/test-app/staging/test-app.yaml
          updates:
          - key: spec.images.0.newTag
            value: ${{ imageFrom("ghcr.io/scottaubrey/test-app").Tag }}
      - uses: git-commit
        as: commit
        config:
          path: ${{ vars.outPath }}
          messageFromSteps:
          - update-image
