apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: github
  namespace: test-app
spec:
  subscriptions:
  - git:
      repoURL: git@github.com:scottaubrey/kargo-exploration.git
      branch: main
  - image:
      repoURL: ghcr.io/scottaubrey/test-app
      gitRepoURL: git@github.com:scottaubrey/kargo-exploration.git
      imageSelectionStrategy: NewestBuild
