apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: github
  namespace: test-app
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/scottaubrey/test-app
      branch: main
  - image:
      repoURL: ghcr.io/scottaubrey/test-app
      gitRepoURL: https://github.com/scottaubrey/test-app
      imageSelectionStrategy: SemVer
